---
name: Continuous Deployment Pipeline - self-hosted version

on:
  workflow_call:

jobs:
  build:
    name: Build binaries
    runs-on: masters-thesis-arc-runner-set
    strategy:
      fail-fast: false
      matrix:
        include:
          - goos: linux
            goarch: amd64
            ext: ""
          - goos: windows
            goarch: amd64
            ext: ".exe"
          - goos: darwin
            goarch: amd64
            ext: ""

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          cache: true

      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 0
        run: |
          go build -o modbusCRC16${{ matrix.ext }} ./src/modbusCRC16.go

      - name: Archive binary
        run: |
          mkdir -p dist
          cp modbusCRC16${{ matrix.ext }} dist/
          cd dist
          tar -czf modbusCRC16-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz modbusCRC16${{ matrix.ext }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: modbusCRC16-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/modbusCRC16-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz