---
name: Simple performance pipeline

on:
  workflow_call:
    inputs:
      pipeline-call-ts:
        description: "Time of the pipeline call."
        required: true
        type: string
    secrets:
      aws-access-key-id:
        description: "AWS Access Key ID for S3 upload."
        required: true
      aws-secret-access-key:
        description: "AWS Secret Access Key for S3 upload."
        required: true
      aws-region:
        description: "AWS Region for S3 upload."
        required: true
      s3-bucket-name:
        description: "S3 Bucket name for performance JSON upload."  
        required: true

jobs:
  start-time:
    name: Capture Start Time
    runs-on: ubuntu-latest
    outputs:
      start-time: ${{ steps.set-start-time.outputs.start-time }}
    steps:
    - name: Set start time
      id: set-start-time
      run: echo "::set-output name=start-time::$(date +%T.%N)"
  ci:
    name: Continuous Integration and Continuous Testing
    needs: start-time
    uses: ./.github/workflows/ci__simple__small-project.yml
  cd:
    name: Continuous Deployment
    needs: ci
    uses: ./.github/workflows/cd__simple__small-project.yml
  stop-time:
    name: Capture Stop Time
    needs: cd
    runs-on: ubuntu-latest
    outputs:
      stop-time: ${{ steps.set-stop-time.outputs.stop-time }}
    steps:
    - name: Set stop time
      id: set-stop-time
      run: echo "::set-output name=stop-time::$(date +%T.%N)"
  generate-report:
    name: Generate Performance Report
    needs: [start-time, ci, cd, stop-time]
    runs-on: ubuntu-latest
    env:
      S3_PREFIX: glue/performance-metrics
    steps:
      - name: Build performance JSON record
        run: |
          # Overall pipeline start/stop times
          PIPELINE_START="${{ needs.start-time.outputs.start-time }}"
          PIPELINE_STOP="${{ needs.stop-time.outputs.stop-time }}"

          # Pipeline duration calculation
          START_EPOCH=$(date -d "$(date +%F) $PIPELINE_START" +%s%N)
          STOP_EPOCH=$(date -d "$(date +%F) $PIPELINE_STOP" +%s%N)
          PIPELINE_DIFF=$((STOP_EPOCH - START_EPOCH))
          DURATION_SEC=$(awk -v d="$PIPELINE_DIFF" 'BEGIN { printf "%.5f", d/1e9 }')

          # Pipeline run metadata
          RUN_DATE=$(date -u +%Y-%m-%d)
          RUN_TS=$(date -u +%Y-%m-%dT%H:%M:%SZ)
          echo "RUN_DATE=$RUN_DATE" >> "$GITHUB_ENV"

          # CI job start/stop times
          CI_START_TIME="${{ needs.ci.outputs.ci-start-time }}"
          CI_STOP_TIME="${{ needs.ci.outputs.ci-stop-time }}"

          # CI Pipeline duration calculation
          CI_START_EPOCH=$(date -d "$(date +%F) $CI_START_TIME" +%s%N)
          CI_STOP_EPOCH=$(date -d "$(date +%F) $CI_STOP_TIME" +%s%N)
          CI_DURATION_DIFF=$((CI_STOP_EPOCH - CI_START_EPOCH))
          CI_DURATION_SEC=$(awk -v d="$CI_DURATION_DIFF" 'BEGIN { printf "%.5f", d/1e9 }')

          # CT job start/stop times
          CT_START_TIME="${{ needs.ci.outputs.long-start-time }}"
          CT_STOP_TIME="${{ needs.ci.outputs.long-stop-time }}"

          # CT Pipeline duration calculation
          CT_START_EPOCH=$(date -d "$(date +%F) $CT_START_TIME" +%s%N)
          CT_STOP_EPOCH=$(date -d "$(date +%F) $CT_STOP_TIME" +%s%N)
          CT_DURATION_DIFF=$((CT_STOP_EPOCH - CT_START_EPOCH))
          CT_DURATION_SEC=$(awk -v d="$CT_DURATION_DIFF" 'BEGIN { printf "%.5f", d/1e9 }')

          # Build JSON line record
          cat <<EOF | jq -c . > performance.jsonl
          {
            "run_id":"${{ github.run_id }}",
            "pipeline_call_time":"${{ inputs.pipeline-call-ts }}",
            "pipeline_start_time":"$PIPELINE_START",
            "pipeline_stop_time":"$PIPELINE_STOP",
            "pipeline_duration":$DURATION_SEC,
            "ci_start_time":"$CI_START_TIME",
            "ci_stop_time":"$CI_STOP_TIME",
            "ci_duration":$CI_DURATION_SEC,
            "ct_start_time":"$CT_START_TIME",
            "ct_stop_time":"$CT_STOP_TIME",
            "ct_duration":$CT_DURATION_SEC
          }
          EOF

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-region:            ${{ secrets.aws-region }}

      - name: Upload JSON to S3 bucket
        run: |
          FILE_NAME="github-${{ github.workflow }}-${{ github.run_id }}.jsonl"
          aws s3 cp performance.jsonl \
            "s3://${{ secrets.s3-bucket-name }}/${S3_PREFIX}/run_date=${RUN_DATE}/${FILE_NAME}"
    